

```{r}
library(DESeq2)
library("dplyr")
library("ggplot2")
library('biomaRt')
library(stringr)
library(pheatmap)
library(RColorBrewer)
library(stats)
library(ggpubr)
library(ggpmisc)
library(ggpointdensity)
library(ggrepel)
library(EnhancedVolcano)
library(msigdbr)
library(clusterProfiler)
library("org.Hs.eg.db")
```

#read file
```{r}
datapath <- "/Users/chaoyuka/Desktop/Data/For_timevault_paper/Fig2/Code/HS/all_gex_matrix_genename_HS.txt"
metadatapath <- "/Users/chaoyuka/Desktop/Data/For_timevault_paper/Fig2/Code/HS/metadata_250125_HS.csv"
out_path <- "/Users/chaoyuka/Desktop/Data/For_timevault_paper/Fig2/Code/HS"

gex <- as.matrix(read.delim(datapath,sep="\t"))
metadata <- read.csv(metadatapath,header = TRUE,row.names = "sample")
rownames(gex) <- gex[,1]
```

#subset samples
```{r}

#HSA = HSpast, recorded/captured
#HSB = HSpresent, recorded/captured
#HSD = Negative control, recorded/captured

#HSA_c = HSpast, cytosol
#HSB_c = HSpresent, cytosol
#HSD_c = Negative control, cytosol

#subset samples
#"HSA1","HSA2","HSA3","HSB1","HSB2","HSB3","HSD1","HSD2","HSD3",
#"HSA1_c","HSA2_c","HSA3_c","HSB1_c","HSB2_c","HSB3_c","HSD1_c","HSD2_c","HSD3_c"

columns_of_interest_AB_cap <- c("HSA1","HSA2","HSA3","HSB1","HSB2","HSB3")
columns_of_interest_AD_cap <- c("HSA1","HSA2","HSA3","HSD1","HSD2","HSD3")
columns_of_interest_BD_cap <- c("HSB1","HSB2","HSB3","HSD1","HSD2","HSD3")
columns_of_interest_AB_lysate <- c("HSA1_c","HSA2_c","HSA3_c","HSB1_c","HSB2_c","HSB3_c")
columns_of_interest_AD_lysate <- c("HSA1_c","HSA2_c","HSA3_c","HSD1_c","HSD2_c","HSD3_c")
columns_of_interest_BD_lysate <- c("HSB1_c","HSB2_c","HSB3_c","HSD1_c","HSD2_c","HSD3_c")

metadata_AB <- metadata[c(1,2,3,4,5,6), , drop = FALSE]
metadata_AD <- metadata[c(1,2,3,7,8,9), , drop = FALSE]
metadata_BD <- metadata[c(4,5,6,7,8,9), , drop = FALSE]
metadata_ABc <- metadata[c(10,11,12,13,14,15), , drop = FALSE]
metadata_ADc <- metadata[c(10,11,12,16,17,18), , drop = FALSE]
metadata_BDc <- metadata[c(13,14,15,16,17,18), , drop = FALSE]

gex_sub_AB <- gex[, columns_of_interest_AB_cap]
gex_sub_AD <- gex[, columns_of_interest_AD_cap]
gex_sub_BD <- gex[, columns_of_interest_BD_cap]
gex_sub_ABc <- gex[, columns_of_interest_AB_lysate]
gex_sub_ADc <- gex[, columns_of_interest_AD_lysate]
gex_sub_BDc <- gex[, columns_of_interest_BD_lysate]

class(gex_sub_AB) <- "numeric"
class(gex_sub_AD) <- "numeric"
class(gex_sub_BD) <- "numeric"
class(gex_sub_ABc) <- "numeric"
class(gex_sub_ADc) <- "numeric"
class(gex_sub_BDc) <- "numeric"

gex_sub<-na.omit(gex_sub_AB) 
gex_sub<-na.omit(gex_sub_AD) 
gex_sub<-na.omit(gex_sub_ABc) 
gex_sub<-na.omit(gex_sub_ABc) 
gex_sub<-na.omit(gex_sub_ADc) 
gex_sub<-na.omit(gex_sub_BDc) 
```



```{r}
#create DEseq object
dds_AB <- DESeqDataSetFromMatrix(countData = gex_sub_AB, colData = metadata_AB, design = ~ group)
dds_AD <- DESeqDataSetFromMatrix(countData = gex_sub_AD, colData = metadata_AD, design = ~ group)
dds_BD <- DESeqDataSetFromMatrix(countData = gex_sub_BD, colData = metadata_BD, design = ~ group)
dds_ABc <- DESeqDataSetFromMatrix(countData = gex_sub_ABc, colData = metadata_ABc, design = ~ group)
dds_ADc <- DESeqDataSetFromMatrix(countData = gex_sub_ADc, colData = metadata_ADc, design = ~ group)
dds_BDc <- DESeqDataSetFromMatrix(countData = gex_sub_BDc, colData = metadata_BDc, design = ~ group)

#filter genes <10

dds_AB <- dds_AB[rowSums(counts(dds_AB)) >= 10,]
dds_AD <- dds_AD[rowSums(counts(dds_AD)) >= 10,]
dds_BD <- dds_BD[rowSums(counts(dds_BD)) >= 10,]
dds_ABc <- dds_ABc[rowSums(counts(dds_ABc)) >= 10,]
dds_ADc <- dds_ADc[rowSums(counts(dds_ADc)) >= 10,]
dds_BDc <- dds_BDc[rowSums(counts(dds_BDc)) >= 10,]

#assign group
dds_AB$group <- factor(dds_AB$group, levels = c("HSA","HSB"))
dds_AD$group <- factor(dds_AD$group, levels = c("HSA","HSD"))
dds_BD$group <- factor(dds_BD$group, levels = c("HSB","HSD"))
dds_ABc$group <- factor(dds_ABc$group, levels = c("HSAc","HSBc"))
dds_ADc$group <- factor(dds_ADc$group, levels = c("HSAc","HSDc"))
dds_BDc$group <- factor(dds_BDc$group, levels = c("HSBc","HSDc"))

#perform DEseq
dds_AB <- DESeq(dds_AB)
dds_AD <- DESeq(dds_AD)
dds_BD <- DESeq(dds_BD)
dds_ABc <- DESeq(dds_ABc)
dds_ADc <- DESeq(dds_ADc)
dds_BDc <- DESeq(dds_BDc)

#extract result (FC and Padj)
res_AB <- results(dds_AB)
res_AD <- results(dds_AD)
res_BD <- results(dds_BD)
res_ABc <- results(dds_ABc)
res_ADc <- results(dds_ADc)
res_BDc <- results(dds_BDc)
```


#gene enrichment analysis
```{r}
#assign res for analysis
res <- res_AB
all_genes <- as.character(rownames(res))

#Extract significant results
signif_res <- res[res$padj < 1E-20 & !is.na(res$padj) & res$log2FoldChange < -1, ] #P<1E-20 FC>1
signif_genes <- as.character(rownames(signif_res))
signif_gene_fc_list <- DataFrame(signif_genes,signif_res$log2FoldChange)

#sort gene list. ## if negative take abs
geneList = abs(signif_gene_fc_list[,2])
## named vector
names(geneList) = as.character(signif_gene_fc_list[,1])
## decreasing order
geneList = sort(geneList, decreasing = TRUE)


# Perform enrichGO
ego <- enrichGO(gene = signif_genes, 
 universe = all_genes,
 keyType = "SYMBOL",
 OrgDb = org.Hs.eg.db, 
 ont = "BP", 
 pAdjustMethod = "BH", 
 pvalueCutoff  = 0.01,
 qvalueCutoff = 0.05, 
 readable = TRUE)
cluster_summary <- data.frame(ego)

dotplot(ego, showCategory=10, font.size = 14,x = "Count")+scale_color_gradient(low = "red", high = "deepskyblue3")

#save enricher result
#write.csv(ego@result, "/Users/chaoyuka/Desktop/Data/For_timevault_paper/Fig2/Code/HS/GO_data_eA_AB_capture_FC1_pval1Em20.csv")
```







#volcano plot
```{r}

#select which part to plot
res<-res_AB

#select gene of interest
#for AvsB captured
gene_of_interest = c("HSPB1","HSPD1","HSP90AA1","HSP90AB1","AHSA1","CRYAB","CACYBP","SERPINH1","ENO1","FKBP4","HSPH1","CLU","AUP1","PDIA6","FLAD1","FTL","RAB11A","ZBTB25","SMAP1","DYNC1LI1","RNY3","ALDH9A1","ADORA2B","ANXA2","PDHB")
#for AvsD captured
#gene_of_interest = c("HSPB1","HSPD1","HSP90AA1","HSP90AB1","AHSA1","CRYAB","CACYBP","SERPINH1","ENO1","FKBP4","HSPH1","CLU","AUP1","PDIA6","FLAD1","FTL","RAB11A","ZBTB25","SMAP1","DYNC1LI1","RNY3","DEGS1","ADORA2B","ANXA2","PDHB")
#for AvsB cytosol
#gene_of_interest = c("DNAJB1","HSPA6","HSPA1A","HSPA1B","HSPA1L","BAG3","HSPH1","HSPB1","HSP90AA1","HSP90AB1","SERPINH1","HAS2","PYCR3","TFRC","SLFN5")

#set cut off value
FCCutoff = 1
pCutoff = 1e-20

#set colors
keyvals.colour <- ifelse(
    res$log2FoldChange < -FCCutoff & res$padj < pCutoff, 'deepskyblue3',
      ifelse(res$log2FoldChange > FCCutoff & res$padj < pCutoff, 'red',
        'grey'))
  keyvals.colour[is.na(keyvals.colour)] <- 'grey'
  names(keyvals.colour)[keyvals.colour == 'red'] <- 'Downregulated'
  names(keyvals.colour)[keyvals.colour == 'grey'] <- 'No change'
  names(keyvals.colour)[keyvals.colour == 'deepskyblue3'] <- 'Upregulated'


#draw  volcano plot
p_vol_AB_cap <- EnhancedVolcano(res,
    lab = rownames(res),
    x = 'log2FoldChange',
    y = 'padj',
    pCutoff = pCutoff, 
    FCcutoff = FCCutoff, 
    ylim = c(0,150),
    xlim = c(-8,8),
    border = 'full',
    colCustom = keyvals.colour,
    pointSize = 8.0,#was8
    labSize = 7.0,#was7
    axisLabSize= 30.0,
    boxedLabels = FALSE, drawConnectors = TRUE,widthConnectors = 0.5,
    legendPosition = 'none',title = NULL,subtitle = NULL,
    gridlines.minor=FALSE, gridlines.major=FALSE,selectLab = gene_of_interest)

#ggsave(file.path(out_path, "vol_AB_captured.pdf"), p_vol_AB_cap, dpi = 300, width = 10, height = 10)
```

#Heatmap
```{r}
#Heatmap
#select which sample to plot
dds <- dds_AB

# Z score plotting
vsd2 <- assay(vst(dds))
Z <- t(scale(t(vsd2)))

# select gene of interest
subset_Z <- Z[c("HSPB1","HSPD1",'HSPA4L',"HSP90AA1","HSP90AB1","HSPH1","AHSA1","BAG3","CRYAB","CACYBP","DNAJB1","SERPINH1"), ]

# select scale
breaksList = seq(-2, 2, by = 0.025)

# plot heatmap
p_heat <- pheatmap(subset_Z,       
        cluster_rows = FALSE,
        cluster_cols = FALSE,
        display_numbers = FALSE,
        cellheight = 15,
        cellwidth = 40,
        fontsize_row = 15,          
        fontsize_col = 15,
        fontsize = 15,
        angle_col = 45,
        gaps_row = c(12),
        treeheight_col = 20,
        breaks = breaksList,
        color = colorRampPalette(c("#1396CB", "white", "#FF5955"))(length(breaksList)))


#ggsave(file.path(out_path, "Heatmap_AD_lysate.pdf"), p_heat, dpi = 300, width = 10, height = 10)
```

#plot 2D dot plot for enrichment
```{r}
#filtered and group labeled GO enrichment analysis (example in GO_analysis.xlsx)
Enrichment_analysis <- read.table(pipe("pbpaste"), sep="\t", header = TRUE)

Enrichment_analysis[Enrichment_analysis == ''] <- NA

Enrich_plot <- ggplot(Enrichment_analysis, aes(x = name, y = Description, color = padj, size = GeneRatio)) +
  geom_point(alpha = 0.8,na.rm = TRUE) +
  labs(
    title = "",
    x = "sample",
    y = "Pathways",
    color = "padj",
    size = "GeneRatio"
  ) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.minor = element_blank(),panel.grid.major = element_blank()) +
  scale_color_gradient(low = "red",  high = "lightgrey",limits = c(1E-20,0.05))+
  scale_size(range = c(8,15))

#ggsave(file.path(out_path, "Enrichplot_GO_dot_HS.pdf"), Enrich_plot, dpi = 300, width = 18, height = 4)
```
